name: Dotnet Build-Test-MSDeploy your project

on:
 # push:
  #  branches: [ master ]
   workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_V }}

      - name: Build 
        run: dotnet build --configuration Release

      - name: publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: app2
          path: ${{env.DOTNET_ROOT}}/myapp
  deploy:

    runs-on: self-hosted
    needs: build


    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app2  
    - uses: echo pwd
    - uses: ${{env.DOTNET_ROOT}}/myapp
    - name: Stop Application Pool
      shell: cmd
      run: C:\Windows\System32\inetsrv\appcmd stop apppool /apppool.name:"DefaultAppPool"
    - name: Deploy Application
      shell: cmd
      run: Copy-Item -Path "C:\Logfiles\*" -Destination "C:\inetpub\wwwroot" -Recurse
    - name: Start Application Pool
      shell: cmd
      run: C:\Windows\System32\inetsrv\appcmd start apppool /apppool.name:"DefaultAppPool"
